# Generated by Django 3.0.8 on 2020-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_slug'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='machine',
            field=models.ManyToManyField(blank=True, related_name='applications', to='machine.Machine', verbose_name='Machines'),
        ),
    ]
