# Generated by Django 3.0.8 on 2020-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=262144, verbose_name='Company Description')),
            ],
        ),
    ]
