# Generated by Django 3.0.8 on 2020-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=262144, verbose_name='Machine Description'),
        ),
    ]
