# Generated by Django 3.0.8 on 2020-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0003_auto_20200724_1600'),
        ('application', '0002_auto_20200724_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=262144, verbose_name='Industry Description')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('application', models.ManyToManyField(blank=True, related_name='Industries', to='application.Application', verbose_name='Applications')),
                ('machine', models.ManyToManyField(blank=True, related_name='Industries', to='machine.Machine', verbose_name='Machines')),
            ],
        ),
    ]
