# Generated by Django 3.0.8 on 2020-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20200724_1600'),
        ('application', '0002_auto_20200724_1458'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='Industries_company', to='application.Application', verbose_name='Companys'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='application',
            field=models.ManyToManyField(blank=True, related_name='Industries_application', to='application.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='machine',
            field=models.ManyToManyField(blank=True, related_name='Industries_machine', to='machine.Machine', verbose_name='Machines'),
        ),
    ]
