# Generated by Django 3.0.8 on 2020-07-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_slug'),
        ('industry', '0002_auto_20200724_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='Industries_company', to='company.Company', verbose_name='Companys'),
        ),
    ]
