# Generated by Django 3.0.8 on 2020-07-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=128, verbose_name='Hash')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name')),
                ('company_description', models.TextField(blank=True, max_length=262144, verbose_name='Company Description')),
                ('company_website', models.URLField(blank=True, max_length=1024, verbose_name='Company Website')),
            ],
        ),
    ]
