# Generated by Django 3.0.8 on 2020-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('application', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='application',
            field=models.ManyToManyField(blank=True, related_name='companys', to='application.Application', verbose_name='Applications'),
        ),
        migrations.AddField(
            model_name='company',
            name='machine',
            field=models.ManyToManyField(blank=True, related_name='companys', to='machine.Machine', verbose_name='Machines'),
        ),
    ]
